spring.application.name=LearnCore
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/learn_core}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Sentry Monitoring
sentry.dsn=${SENTRY_DSN:https://examplePublicKey@o0.ingest.sentry.io/0}
sentry.traces-sample-rate=1.0